title: Project
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: title_fr
            field:
              type: text
              display: 'Title FR'
          -
            handle: title_en
            field:
              type: text
              display: 'Title EN'
          -
            handle: description_fr
            field:
              type: textarea
              display: 'Description FR'
          -
            handle: description_en
            field:
              type: textarea
              display: 'Description EN'
          -
            handle: technologies
            field:
              type: text
              display: Technologies
          -
            handle: project_url
            field:
              type: text
              display: 'Project URL'
          -
            handle: image
            field:
              container: assets
              type: assets
              display: Image
          -
            handle: order
            field:
              type: integer
              display: Order
